### ISSUE TITLE
Issue with GeoSchelling example

### ISSUE THREAD

**Issue by Albertolopezs** [Corvince/mesa-geo#13]
Hi, I'm trying to run the GeoSchelling examply and i'm getting an error, i suppose it would be a library that i need to install but i cant find out which one is, hope you can help me.

> Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from server import server
  File "C:\Users\alrot\OneDrive\Escritorio\TFG - Alberto López Santiago\mesa-geo-master\examples\GeoSchelling\server.py", line 46, in <module>
    SchellingModel, [map_element, happy_element, happy_chart], "Schelling", model_params
  File "c:\users\alrot\src\mesa-geo\mesa_geo\visualization\ModularVisualization.py", line 276, in __init__
    self.reset_model()
  File "c:\users\alrot\src\mesa-geo\mesa_geo\visualization\ModularVisualization.py", line 302, in reset_model
    self.model = self.model_cls(**model_params)
  File "C:\Users\alrot\OneDrive\Escritorio\TFG - Alberto López Santiago\mesa-geo-master\examples\GeoSchelling\model.py", line 61, in __init__
    self.grid = GeoSpace(crs={"init": "epsg:4326"})
  File "c:\users\alrot\src\mesa-geo\mesa_geo\geospace.py", line 36, in __init__
    self.crs = pyproj.Proj(crs)
  File "C:\Users\alrot\Anaconda3\lib\site-packages\pyproj\__init__.py", line 358, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 84, in _proj.Proj.__cinit__
RuntimeError: b'No such file or directory'

**Comment by Corvince** [comment]
@Albertolopezs 
Not really sure what the problem is, but it seems like to be a problem with Pyproj. Can you describe how exactly you installed mesa-geo?

@cpritcha 
Thanks for the report. As you can read in the release notes, it is currently not possible to use attribute names for data collection. But I forgot to take that advice myself and remove the Datacollector from the GeoSchelling example. 

If you comment out or remove the following line (#64) from `model.py` it should work. 
```Python        
self.datacollector = DataCollector({"happy": "happy"})
```
Can you confirm this?

**Comment by cpritcha** [comment]
Thanks! 

Setting `self.datacollector` to an empty `DataCollector` object results in a working example.

```diff
--- a/examples/GeoSchelling/model.py
+++ b/examples/GeoSchelling/model.py
@@ -61,7 +61,7 @@ class SchellingModel(Model):
         self.grid = GeoSpace(crs={"init": "epsg:4326"})
 
         self.happy = 0
-        self.datacollector = DataCollector({"happy": "happy"})
+        self.datacollector = DataCollector()
 
         self.running = True
```

Removing the line entirely resulted in an error:

```
ERROR:tornado.application:Uncaught exception in /ws
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/websocket.py", line 494, in _run_callback
    result = callback(*args, **kwargs)
  File "/app/mesa_geo/visualization/ModularVisualization.py", line 204, in on_message
    self.write_message(self.viz_state_message)
  File "/app/mesa_geo/visualization/ModularVisualization.py", line 184, in viz_state_message
    "data": self.application.render_model()
  File "/app/mesa_geo/visualization/ModularVisualization.py", line 311, in render_model
    element_state = element.render(self.model)
  File "/usr/local/lib/python3.6/dist-packages/mesa/visualization/modules/ChartVisualization.py", line 73, in render
    data_collector = getattr(model, self.data_collector_name)
AttributeError: 'SchellingModel' object has no attribute 'datacollector'
```

**Comment by Corvince** [comment]
I see, I see. Thanks for the feedback! Thats really helpful and I'll try to fix this soon

**Comment by Corvince** [comment]
@Albertolopezs 

This seems to be a problem with Geopandas/pyproj, see geopandas/geopandas#830 

[This comment](https://github.com/geopandas/geopandas/issues/830#issuecomment-426116505) proposes a solution that worked for me (I had the same problem on a clean build)

**Comment by thomasjurriaan** [comment]
The tutorial and the test files run without errors, but when I try to run the GeoSchelling example I encounter the following error:

mesa-geo/examples/GeoSchelling$ python run.py
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/home/thomas/anaconda3/lib/python3.7/site-packages/Rtree-0.8.3-py3.7.egg/rtree/index.py", line 722, in py_next_item
    p_length[0], data, _ = self._serialize(obj)
  File "/home/thomas/anaconda3/lib/python3.7/site-packages/Rtree-0.8.3-py3.7.egg/rtree/index.py", line 331, in _serialize
    serialized = self.dumps(obj)
  File "/home/thomas/anaconda3/lib/python3.7/site-packages/Rtree-0.8.3-py3.7.egg/rtree/index.py", line 278, in dumps
    return pickle.dumps(obj)
AttributeError: Can't pickle local object 'DataCollector._make_attribute_collector.<locals>.attr_collector'
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from server import server
  File "/home/thomas/OneDrive/Documents/Master/Computational Science/Jaar 2/Thesis/Models/mesa-geo/examples/GeoSchelling/server.py", line 46, in <module>
    SchellingModel, [map_element, happy_element, happy_chart], "Schelling", model_params
  File "/home/thomas/anaconda3/lib/python3.7/site-packages/mesa_geo-0.1.0-py3.7.egg/mesa_geo/visualization/ModularVisualization.py", line 276, in __init__
    self.reset_model()
  File "/home/thomas/anaconda3/lib/python3.7/site-packages/mesa_geo-0.1.0-py3.7.egg/mesa_geo/visualization/ModularVisualization.py", line 302, in reset_model
    self.model = self.model_cls(**model_params)
  File "/home/thomas/OneDrive/Documents/Master/Computational Science/Jaar 2/Thesis/Models/mesa-geo/examples/GeoSchelling/model.py", line 71, in __init__
    self.grid.add_agents(agents)
  File "/home/thomas/anaconda3/lib/python3.7/site-packages/mesa_geo-0.1.0-py3.7.egg/mesa_geo/geospace.py", line 59, in add_agents
    self._recreate_rtree(agents)
  File "/home/thomas/anaconda3/lib/python3.7/site-packages/mesa_geo-0.1.0-py3.7.egg/mesa_geo/geospace.py", line 154, in _recreate_rtree
    self.idx = index.Index(data_gen())
  File "/home/thomas/anaconda3/lib/python3.7/site-packages/Rtree-0.8.3-py3.7.egg/rtree/index.py", line 264, in __init__
    self.handle = self._create_idx_from_stream(stream)
  File "/home/thomas/anaconda3/lib/python3.7/site-packages/Rtree-0.8.3-py3.7.egg/rtree/index.py", line 728, in _create_idx_from_stream
    return IndexStreamHandle(self.properties.handle, stream)
  File "/home/thomas/anaconda3/lib/python3.7/site-packages/Rtree-0.8.3-py3.7.egg/rtree/index.py", line 854, in __init__
    self._ptr = self._create(*args, **kwargs)
  File "/home/thomas/anaconda3/lib/python3.7/site-packages/Rtree-0.8.3-py3.7.egg/rtree/core.py", line 28, in check_void
    raise RTreeError(msg)
rtree.core.RTreeError: Error in "Index_CreateWithStream": IllegalArgumentException: RTree::BulkLoader::bulkLoadUsingSTR: Empty data stream given.
Exception ignored in: <function Handle.__del__ at 0x7fb833999840>
Traceback (most recent call last):
  File "/home/thomas/anaconda3/lib/python3.7/site-packages/Rtree-0.8.3-py3.7.egg/rtree/index.py", line 875, in __del__
    self.destroy()
  File "/home/thomas/anaconda3/lib/python3.7/site-packages/Rtree-0.8.3-py3.7.egg/rtree/index.py", line 863, in destroy
    if self._ptr is not None:
AttributeError: 'IndexStreamHandle' object has no attribute '_ptr'

I have installed rtree, libspatialindex and mesa-geo multiple times in different manners (both pip and through setup.py files) Other geomesa examples seem to work as well.

**Comment by Corvince** [comment]
Hi there, sorry for the late response. This error occurs, because mesa-geo can only handle pickable model objects. And until now the latest released version of mesa has an unpickleable DataCollector. 

I will update the requirements once the next release of mesa is published and also catch this error and give a more meaningful error message. 

Until then you have to install the latest development version of mesa with 
`$ pip install -e git+https://github.com/projectmesa/mesa`

**Comment by dhruv4** [comment]
Hey @Corvince! Thanks for putting together this cool module. I'm having a different error with the example where it seems like it's not displaying correctly. All the polygons/agents are showing up in a giant overlapping line at the top rather than on the map. As far as I know, I haven't changed any code and have installed the most up to date development version of mesa.

![Screen Shot 2019-06-04 at 11 37 35 PM](https://user-images.githubusercontent.com/4268798/58928740-c5941e80-8721-11e9-81db-127df234ddb7.png)

**Comment by dhruv4** [comment]
Okay! Looks like I actually solved my own issue by fixing the CRS.

On line 61 of model.py, I removed the CRS and changed the line to: ` self.grid = GeoSpace()` from `self.grid = GeoSpace(crs={"init": "epsg:4326"})` and it just worked!

**Comment by ArcPam** [comment]
The chart is not pulling in the data properly. The x and y axis are not changing. The datacollector just defaults to 0. Any advice?

**Comment by Ansh2506** [comment]
Hi, I tried to run the GeoSchelling examples, but I am having multiple errors, mainly in loading the fiona module.  I have tried to install this through multiple ways but I am still getting the error. Can anyone please help with this?

![image](https://user-images.githubusercontent.com/57211865/160379739-4e92a4bd-d107-4865-8eaf-c2c11afdbbca.png)
